name: final_cross
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  dio: ^5.5.0
  http: ^1.2.1
  pretty_dio_logger: ^1.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.3
  url_launcher: ^6.3.1
  
  # Fixed Firebase versions for compatibility
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - .env
