// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOxhBRPl1PmE4zTT1McNH6ONwbtqKoK2Y',
    appId: '1:858305336010:web:da01aebfd90e5044931a33',
    messagingSenderId: '858305336010',
    projectId: 'elearning-5ac35',
    authDomain: 'elearning-5ac35.firebaseapp.com',
    storageBucket: 'elearning-5ac35.firebasestorage.app',
    measurementId: 'G-G6BHDFL9XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzB9SASq88va8OZkiDKhQE24faVIc25rQ',
    appId: '1:858305336010:android:efec12c7f0b9b330931a33',
    messagingSenderId: '858305336010',
    projectId: 'elearning-5ac35',
    storageBucket: 'elearning-5ac35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC6wIRTDmzaj4yoalFYMlXNTH1JVSiIks',
    appId: '1:858305336010:ios:30c8ed7a1743b168931a33',
    messagingSenderId: '858305336010',
    projectId: 'elearning-5ac35',
    storageBucket: 'elearning-5ac35.firebasestorage.app',
    iosBundleId: 'com.example.finalCross',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC6wIRTDmzaj4yoalFYMlXNTH1JVSiIks',
    appId: '1:858305336010:ios:30c8ed7a1743b168931a33',
    messagingSenderId: '858305336010',
    projectId: 'elearning-5ac35',
    storageBucket: 'elearning-5ac35.firebasestorage.app',
    iosBundleId: 'com.example.finalCross',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOxhBRPl1PmE4zTT1McNH6ONwbtqKoK2Y',
    appId: '1:858305336010:web:fc561383d3d8dcc3931a33',
    messagingSenderId: '858305336010',
    projectId: 'elearning-5ac35',
    authDomain: 'elearning-5ac35.firebaseapp.com',
    storageBucket: 'elearning-5ac35.firebasestorage.app',
    measurementId: 'G-FG93MQYK5E',
  );
}
